(* lib/catseye_incremental/analysis_graph.ml
   Incremental DAG for Catseye analysis state management.

   This module provides a self-updating graph using Jane Street's Incremental library.
   When a file changes, only the minimal subset of inheritance trees, taint maps,
   and LCOM cohesion metrics are recomputed. *)

open Base
open Incremental

(* ── Node Types ─────────────────────────────────────────────────────── *)

(** Represents a source file in the analysis graph *)
type file_node = {
  path : string;
  lang : string;
  hash : string;           (* File content hash for change detection *)
  mtime : float;            (* Modification time for ordering *)
}

(** Represents an AST module derived from a file *)
type ast_node = {
  file : file_node;
  ast : Catseye_ast.Types.module_;
}

(** Represents a finding generated by security rules *)
type finding_node = {
  rule : string;
  severity : string;
  file : string;
  line : int;
  message : string;
}

(** Represents a code smell detected by claws *)
type smell_node = {
  detector : string;
  file : string;
  line : int;
  metric : string;
  value : float;
}

(** Union type for all graph nodes *)
type graph_node =
  | File of file_node
  | AST of ast_node
  | Finding of finding_node
  | Smell of smell_node

(* ── Incremental Graph Structure ─────────────────────────────────────── *)

(** The main analysis graph.
    Uses Incremental.t to track dependencies and automatically
    recompute only affected nodes on changes. *)
module AnalysisGraph = struct
  type t = {
    files : file_node Inc.t;
    asts : ast_node Inc.t;
    findings : finding_node Inc.t;
    smells : smell_node Inc.t;
  }

  let create ~(files : file_node list) =
    let files_inc = Inc.create files in
    let asts_inc = Inc.create [] in
    let findings_inc = Inc.create [] in
    let smells_inc = Inc.create [] in
    { files = files_inc; asts = asts_inc; findings = findings_inc; smells = smells_inc }

  (** Stabilize the graph, recomputing all nodes.
      Call this after making changes to trigger recalculation. *)
  let stabilize (g : t) =
    Inc.stabilize ();
    g

  (* ── File operations ──────────────────────────────────────────────── *)

  (** Mark a file as changed, triggering recomputation *)
  let invalidate_file (g : t) (path : string) =
    Inc.change g.files (fun files ->
      files  (* Keep all files, but hash change will propagate *)
    )

  (** Get current file list *)
  let get_files (g : t) = Inc.peek_exn g.files

  (* ── AST operations ───────────────────────────────────────────────── *)

  (** Update AST for a specific file *)
  let update_ast (g : t) (path : string) (ast : Catseye_ast.Types.module_) =
    Inc.change g.asts (fun asts ->
      let existing = List.filter asts ~f:(fun a -> a.file.path <> path) in
      { file = { path; lang = ""; hash = ""; mtime = 0. }; ast } :: existing
    )

  (* ── Query operations ─────────────────────────────────────────────── *)

  (** Find findings for a specific file *)
  let findings_for_file (g : t) (path : string) : finding_node list =
    let all = Inc.peek_exn g.findings in
    List.filter all ~f:(fun f -> f.file = path)

  (** Find smells for a specific file *)
  let smells_for_file (g : t) (path : string) : smell_node list =
    let all = Inc.peek_exn g.smells in
    List.filter all ~f:(fun s -> s.file = path)
end

(* ── Incremental Computation Helpers ────────────────────────────────── *)

(** Represents a computation that depends on file changes *)
module Computation = struct
  type 'a t = 'a Inc.t

  let return (x : 'a) : 'a t = Inc.create [x] |> fun i ->
    (* Set up a no-op stabilization for constant values *)
    i

  let map (inc : 'a Inc.t) ~(f : 'a -> 'b) : 'b Inc.t =
    Inc.map inc ~f

  let bind (inc : 'a Inc.t) ~(f : 'a -> 'b Inc.t) : 'b Inc.t =
    (* Flatten dependent computations *)
    let rec step a =
      let prev = ref None in
      fun () ->
        match !prev with
        | Some v -> v
        | None ->
          let v = f a in
          prev := Some v;
          v
    in
    Inc.map inc ~f:(fun a -> (step a) ())
end

(* ── Diff Computation ───────────────────────────────────────────────── *)

module Diff = struct
  type change =
    | Added of string
    | Modified of string
    | Removed of string

  (** Compute the difference between two file lists.
      Uses content hashing to detect modifications. *)
  let compute_diff (old_files : file_node list) (new_files : file_node list) =
    let old_map = String.Map.of_list_exn (List.map old_files ~f:(fun f -> f.path, f)) in
    let new_map = String.Map.of_list_exn (List.map new_files ~f:(fun f -> f.path, f)) in
    
    let removed =
      Map.filter_keys old_map ~f:(fun p -> not (Map.mem new_map p))
      |> Map.keys
      |> List.map ~f:(fun p -> Removed p)
    in
    let added =
      Map.filter_keys new_map ~f:(fun p -> not (Map.mem old_map p))
      |> Map.keys
      |> List.map ~f:(fun p -> Added p)
    in
    let modified =
      Map.merge old_map new_map ~f:(fun ~key ->
        function
        | `Left _ -> None
        | `Right _ -> None
        | `Both (old, new_) ->
          if old.hash <> new_.hash then Some (Modified key) else None
      )
      |> Map.data
      |> List.filter_opt
    in
    removed @ added @ modified

  (** Filter findings that are affected by changed files *)
  let affected_findings (findings : finding_node list) (changes : change list) =
    let changed_files =
      List.filter_map changes ~f:(function
        | Added p | Modified p | Removed p -> Some p
      )
      |> String.Set.of_list
    in
    List.filter findings ~f:(fun f ->
      Set.mem changed_files f.file
    )
end

(* ── Version tracking ───────────────────────────────────────────────── *)

let version = "0.1.0"