(* tools/generate_rules/main.ml *)
(* Pure stdlib version *)

let escape_ocaml_string s =
  let len = String.length s in
  let b = Buffer.create (len * 2) in
  for i = 0 to len - 1 do
    let c = s.[i] in
    if c = '\\' then Buffer.add_string b "\\\\"
    else if c = '"' then Buffer.add_string b "\\\""
    else if c = '\n' then Buffer.add_char b ' '
    else Buffer.add_char b c
  done;
  Buffer.contents b

let read_all path =
  let ch = open_in path in
  let n = in_channel_length ch in
  let s = really_input_string ch n in
  close_in ch;
  s

let trim s =
  let len = String.length s in
  let rec left i =
    if i >= len || s.[i] <> ' ' then i else left (i + 1)
  in
  let rec right i =
    if i <= 0 || s.[i - 1] <> ' ' then i else right (i - 1)
  in
  let start = left 0 in
  let stop = right len in
  if start >= stop then "" else String.sub s start (stop - start)

let nl = "\n"
let q = "\""

let main () =
  let argv = Sys.argv in
  let rules_dir = 
    if Array.length argv > 1 then argv.(1)
    else (output_string stderr "Usage: generate_rules <rules_dir> <output>"; output_string stderr nl; exit 1)
  in
  let output = argv.(2) in
  
  if not (Sys.file_exists rules_dir) then
    (output_string stderr ("Error: rules directory '" ^ rules_dir ^ "' not found"); output_string stderr nl; exit 1);
  
  let files = 
    Array.to_list (Sys.readdir rules_dir)
    |> List.filter (fun f -> Filename.check_suffix f ".kdl")
    |> List.sort String.compare
  in
  
  if files = [] then
    (output_string stderr ("Warning: no .kdl files found in " ^ rules_dir); output_string stderr nl; exit 1);
  
  let oc = open_out output in
  output_string oc "(* AUTO-GENERATED by tools/generate_rules/main.ml *)\n";
  output_string oc "(* DO NOT EDIT MANUALLY *)\n";
  output_string oc "\n";
  output_string oc "let get_all_kdl () : string =\n";
  output_string oc "  let rules = [\n";
  
  List.iter (fun f ->
    let path = Filename.concat rules_dir f in
    let content = read_all path in
    let collapsed = trim content in
    let escaped = escape_ocaml_string collapsed in
    output_string oc "    ";
    output_string oc q;
    output_string oc escaped;
    output_string oc q;
    output_string oc ";";
    output_string oc nl;
    output_string stderr ("  Rule: " ^ f);
    output_string stderr nl
  ) files;
  
  output_string oc "  ] in\n";
  output_string oc "  String.concat ";
  output_string oc q;
  output_string oc "\\n";
  output_string oc q;
  output_string oc " rules";
  output_string oc nl;
  close_out oc;
  output_string stderr ("  Generated: " ^ output);
  output_string stderr nl

let () = main ()
