(* lib/catseye_cli/markdown.ml
   Markdown report output from findings. *)

open Catseye_types

let severity_emoji = function
  | "Critical" | "critical" -> "🔴"
  | "High" | "high" -> "🟠"
  | "Medium" | "medium" -> "🟡"
  | "Low" | "low" -> "🔵"
  | _ -> "⚪"

let to_markdown (findings : Finding.t list) (target : string) : string =
  let buf = Buffer.create 4096 in
  let pr fmt = Printf.bprintf buf fmt in
  pr "# Catseye Security Report\n\n";
  pr "**Target**: `%s`  \n" target;
  pr "**Engine**: OCaml taint v3  \n";
  pr "**Findings**: %d  \n\n" (List.length findings);
  pr "---\n\n";
  List.iter (fun (f : Finding.t) ->
    pr "### %s [%s] %s\n\n" (severity_emoji f.severity) f.rule f.severity;
    pr "- **File**: `%s:%d`\n" f.file f.line;
    pr "- **Message**: %s\n" f.message;
    (match f.dependency with
     | Some dep -> pr "- **Dependency**: %s\n" dep
     | None -> ());
    if f.flow <> [] then begin
      pr "- **Taint flow**:\n";
      List.iter (fun (step : Finding.flow_step) ->
        pr "  - ← `%s:%d` — %s\n" step.file step.line step.message
      ) f.flow
    end;
    pr "\n"
  ) findings;
  if findings = [] then
    pr "✨ **No issues found.**\n\n";
  pr "---\n\n*Generated by [Catseye](https://github.com/kritoke/catseye) v%s*\n"
    Catseye_engine.Engine.version;
  Buffer.contents buf
