(* lib/catseye_cli/markdown.ml
   Markdown report output from findings. *)

open Catseye_types

let severity_emoji = function
  | "Critical" | "critical" -> "🔴"
  | "High" | "high" -> "🟠"
  | "Medium" | "medium" -> "🟡"
  | "Low" | "low" -> "🔵"
  | _ -> "⚪"

let reachability_label = function
  | Finding.Live -> "🔴 **LIVE**"
  | Finding.Dormant -> "🟡 **DORMANT**"
  | Finding.Safe -> "✅ **SAFE**"

let to_markdown (findings : Finding.t list) (target : string)
    ?(supply_chain : Yojson.Safe.t option) () : string =
  let buf = Buffer.create 4096 in
  let pr fmt = Printf.bprintf buf fmt in
  pr "# Catseye Security Report\n\n";
  pr "**Target**: `%s`  \n" target;
  pr "**Engine**: OCaml taint v3  \n";
  pr "**Findings**: %d  \n\n" (List.length findings);
  pr "---\n\n";
  List.iter (fun (f : Finding.t) ->
    pr "### %s [%s] %s" (severity_emoji f.severity) f.rule f.severity;
    (match f.reachability with
     | Some r -> pr " (%s)" (reachability_label r.status)
     | None -> ());
    pr "\n\n";
    pr "- **File**: `%s:%d`\n" f.file f.line;
    pr "- **Message**: %s\n" f.message;
    (match f.dependency with
     | Some dep -> pr "- **Dependency**: %s\n" dep
     | None -> ());
    (match f.reachability with
     | Some r when r.status = Finding.Live ->
       pr "- **Reachability**: %s from %s\n"
         (match r.status with Finding.Live -> "Live" | Finding.Dormant -> "Dormant" | Finding.Safe -> "Safe")
         (match r.entry_function with Some fn -> "`" ^ fn ^ "`" | None -> "unknown entry point");
       if r.path <> [] then begin
         pr "- **Path**: %s\n"
           (String.concat " → " (List.map (fun (pf, pl) ->
             Printf.sprintf "`%s:%d`" (Filename.basename pf) pl
           ) r.path))
       end
     | _ -> ());
    if f.flow <> [] then begin
      pr "- **Taint flow**:\n";
      List.iter (fun (step : Finding.flow_step) ->
        pr "  - ← `%s:%d` — %s\n" step.file step.line step.message
      ) f.flow
    end;
    pr "\n"
  ) findings;
  if findings = [] then
    pr "✨ **No issues found.**\n\n";
  (* Supply chain section *)
  (match supply_chain with
   | Some sc ->
     let open Yojson.Safe.Util in
     let deps = match member "dependencies" sc with `List l -> l | _ -> [] in
     if deps <> [] then begin
       pr "---\n\n";
       pr "## 🏴‍☠️ Supply Chain Audit\n\n";
       pr "| Dependency | Version | Level | Status |\n";
       pr "|---|---|---|---|\n";
       List.iter (fun dep ->
         let name = to_string (member "name" dep) in
         let ver = match member "version" dep with `String s -> s | _ -> "?" in
         let level = to_string (member "level" dep) in
         let osv = member "osv" dep in
         let status_text = match member "status" osv with
           | `String "vulnerable" ->
             (match member "vulnerabilities" osv with
              | `List (v :: _) ->
                let cve = to_string (member "id" v) in
                let summary = to_string (member "summary" v) in
                Printf.sprintf "⚠️ %s: %s" cve summary
              | _ -> "Vulnerable")
           | `String "clean" -> "✅ No known CVEs"
           | `String "failed" ->
             (match member "error" osv with
              | `String e -> Printf.sprintf "❌ Query failed: %s" e
              | _ -> "❌ Query failed")
           | _ -> "Unknown"
         in
         pr "| %s | %s | %s | %s |\n" name ver
           (match level with "critical" -> "🔴 Critical" | "warning" -> "⚠️ Warning" | _ -> "✅ Clean")
           status_text
       ) deps;
       pr "\n"
     end
   | None -> ());
  pr "---\n\n*Generated by [Catseye](https://github.com/kritoke/catseye) v%s*\n"
    Catseye_engine.Engine.version;
  Buffer.contents buf
